# -*- coding: utf-8 -*-
from . import test_record_rules
from . import test_balance_model
from . import test_transfer
from . import test_recurring
from . import test_import
from . import test_split
from . import test_category
from . import test_institution
from . import test_payee
from . import test_budget
from . import test_reconciliation
from . import test_dashboard
from . import test_investment
from . import test_net_worth
from . import test_delete_guards
from . import test_security_allocation
from . import test_payee_analytics
from . import test_gem_strategy
from . import test_account_share
from . import test_loan_and_simulations
from . import test_sure_features
from . import test_power_user_features
from . import test_insights
from . import test_ai_features
from . import test_wealthfolio_features
from . import test_dashboard_action
from . import test_benchmark
from . import test_action_history
from . import test_emergency_access
from . import test_duplicate_detector
from . import test_cashflow_calendar
from . import test_tax_lot
from . import test_tax_schedule
